export const fonts = [
  "Roboto",
  "Open Sans",
  "Poppins",
  "Inter",
  "Merriweather",
  "Playfair Display",
  "Lora",
  "Courier Prime",
  "IBM Plex Mono",
  "Bebas Neue",
  "Raleway",
  "Montserrat",
  "Pacifico",
  "Amatic SC",
];
